#Logging configuration
logging:
  version: 1
  formatters:
    ETL_job:
      format: "ETL Stock Data Transformer - %(asctime)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: ETL_job
      level: DEBUG
  root:
    level: DEBUG
    handlers: [console]
            